name: build
on:
  schedule:
    - cron: '0 9 * * *' # Время в UTC (9:00 UTC = 12:00 МСК)
  workflow_dispatch: # Чтобы можно было запустить вручную

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install feedparser requests

      - name: Run bot
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py

      - name: Save last link status
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add last_link.txt
          git commit -m "Update last published news" || exit 0
          git push
