name: build

on:
  # Расписание: каждый день в 10:00 по Москве
  schedule:
    - cron: '0 7 * * *'
  # Кнопка для ручного запуска
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    # Права для GitHub Actions на запись
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Сохраняем учетные данные для последующего коммита
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install feedparser requests

      - name: Run bot
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py

      - name: Save last link status
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # Эта строка создает пустой файл, если его нет, чтобы git не ругался
          touch last_link.txt 
          git add last_link.txt
          git commit -m "Update last link" || echo "No changes to commit"
          git push
